[package]
name    = "hello"
version = "0.1.0"

[lib]
name = "hello"
crate-type = ["staticlib"]

[dependencies.core]
git = "https://github.com/phil-opp/nightly-libcore.git"
features = ["disable_float"]
