[package]
name    = "hello"
version = "0.1.0"

[lib]
crate-type = ["staticlib"]

[dependencies.core]
git = "https://github.com/phil-opp/nightly-libcore.git"
features = ["disable_float"]

[dependencies.kmalloc_allocator]
path = "std/kmalloc_allocator"

[dependencies.alloc]
path = "std/liballoc"

