[package]
authors = ["The Rust Project Developers"]
name = "rustc_unicode"
version = "0.0.0"

[lib]
name = "rustc_unicode"
path = "lib.rs"
test = false

[dependencies.core]
git = "https://github.com/phil-opp/nightly-libcore.git"
features = ["disable_float"]
