#![feature(allocator)]
// We define the allocator fns required.
#![allocator]
// Don't depend on std and the autogenerated bindings, as we don't want circular dependencies.
#![no_std]



// This crate is responsible for connecting to kmalloc.
#[no_mangle]
pub extern "C" fn __rust_allocate(_size: usize, _align: usize) -> *mut u8 {
    0 as *mut _
}

#[no_mangle]
pub extern "C" fn __rust_usable_size(_size: usize, _align: usize) -> usize {
    0
}

#[no_mangle]
pub extern "C" fn __rust_deallocate(_ptr: *mut u8,
                                    _size: usize,
                                    _align: usize) {
}

#[no_mangle]
pub extern "C" fn __rust_reallocate(_ptr: *mut u8,
                                    _size: usize,
                                    _new_size: usize,
                                    _align: usize)
                                    -> *mut u8 {
    0 as *mut _
}

#[no_mangle]
pub extern "C" fn __rust_reallocate_inplace(_ptr: *mut u8,
                                            _size: usize,
                                            _new_size: usize,
                                            _align: usize)
                                            -> usize {
    0

}
